#!/usr/bin/env python3
"""
Semantic point clouds -> closed B-rep -> EnergyPlus IDF.

This replaces the grid massing of cloud_to_idf.py. Walls now lie on the
real facade planes, so the tower stops looking like a stack of slabs and
the windows land where they belong.

Method
------
1.  Find the vertical facade planes in the envelope cloud. Each one becomes
    a straight line in plan.
2.  Build the arrangement of those lines inside the building's bounding box.
    The lines cut the plan into convex cells. This is the 2D version of the
    plane arrangement used by PolyFit, and it is small enough to solve by
    labelling instead of integer programming.
3.  Label each cell full or empty from the point occupancy, and give every
    full cell a height.
4.  Extrude. Floor under every full cell, roof on top of it, and a vertical
    wall on every arrangement edge where the height changes. Closed by
    construction, and every surface is convex.
5.  Windows are found per wall, on the wall's own plane, so one window is
    one connected patch of glazing instead of a 3D blob.
6.  Columns become shading, using the minimum rotated rectangle of each
    cluster rather than an axis-aligned box.

Usage
-----
    python brep_to_idf.py \
        --envelope "roof - Cloud.ply" \
        --windows  "window - Cloud.ply" \
        --columns  "column - Cloud.ply" \
        --height 53.0 --out lsu_tower.idf --preview massing.ply
"""

import argparse
import os
from collections import defaultdict

import numpy as np
import open3d as o3d
from scipy import ndimage
from scipy.signal import find_peaks
from shapely.geometry import LineString, Point, Polygon, box
from shapely.ops import polygonize, unary_union
from shapely.strtree import STRtree

# --------------------------------------------------------------------------
# shared helpers (inlined, so this script has no local imports)
# --------------------------------------------------------------------------

HEADER = """! Generated by brep_to_idf.py from semantic point clouds.
! Geometry only - constructions, loads and schedules are placeholders.

Version, {version};

SimulationControl,
    No,                      !- Do Zone Sizing Calculation
    No,                      !- Do System Sizing Calculation
    No,                      !- Do Plant Sizing Calculation
    Yes,                     !- Run Simulation for Sizing Periods
    No,                      !- Run Simulation for Weather File Run Periods
    No,                      !- Do HVAC Sizing Simulation for Sizing Periods
    1;                       !- Maximum Number of HVAC Sizing Simulation Passes

Building,
    {name},
    {north:.2f},             !- North Axis {{deg}}
    City,                    !- Terrain
    0.04,                    !- Loads Convergence Tolerance Value
    0.4,                     !- Temperature Convergence Tolerance Value
    FullExterior,            !- Solar Distribution
    25,                      !- Maximum Number of Warmup Days
    6;                       !- Minimum Number of Warmup Days

Timestep, 6;

GlobalGeometryRules,
    UpperLeftCorner,         !- Starting Vertex Position
    Counterclockwise,        !- Vertex Entry Direction
    World;                   !- Coordinate System

Site:Location,
    Baton Rouge LA,
    30.53,                   !- Latitude {{deg}}
    -91.15,                  !- Longitude {{deg}}
    -6.0,                    !- Time Zone {{hr}}
    22.0;                    !- Elevation {{m}}

SizingPeriod:DesignDay,
    Baton Rouge Summer,      !- Name
    7, 21, SummerDesignDay,  !- Month, Day, Day Type
    34.4,                    !- Maximum Dry-Bulb Temperature {{C}}
    9.4,                     !- Daily Dry-Bulb Temperature Range {{deltaC}}
    ,                        !- Dry-Bulb Temperature Range Modifier Type
    ,                        !- Dry-Bulb Temperature Range Modifier Schedule
    Wetbulb,                 !- Humidity Condition Type
    25.6,                    !- Wetbulb at Maximum Dry-Bulb {{C}}
    , , , ,                  !- unused humidity fields
    101217.,                 !- Barometric Pressure {{Pa}}
    3.4,                     !- Wind Speed {{m/s}}
    200,                     !- Wind Direction {{deg}}
    No, No, No,              !- Rain, Snow, Daylight Saving
    ASHRAEClearSky,          !- Solar Model Indicator
    , , , ,                  !- unused solar fields
    1.00;                    !- Sky Clearness

SizingPeriod:DesignDay,
    Baton Rouge Winter,      !- Name
    1, 21, WinterDesignDay,  !- Month, Day, Day Type
    -2.2,                    !- Maximum Dry-Bulb Temperature {{C}}
    0.0,                     !- Daily Dry-Bulb Temperature Range {{deltaC}}
    ,                        !- Dry-Bulb Temperature Range Modifier Type
    ,                        !- Dry-Bulb Temperature Range Modifier Schedule
    Wetbulb,                 !- Humidity Condition Type
    -2.2,                    !- Wetbulb at Maximum Dry-Bulb {{C}}
    , , , ,                  !- unused humidity fields
    101217.,                 !- Barometric Pressure {{Pa}}
    4.9,                     !- Wind Speed {{m/s}}
    350,                     !- Wind Direction {{deg}}
    No, No, No,              !- Rain, Snow, Daylight Saving
    ASHRAEClearSky,          !- Solar Model Indicator
    , , , ,                  !- unused solar fields
    0.00;                    !- Sky Clearness

!  ---- placeholder constructions ----

Material, Brick 200mm, MediumRough, 0.2000, 0.890, 1920.0, 790.0;
Material, Insulation 80mm, MediumRough, 0.0800, 0.040, 40.0, 1200.0;
Material, Plaster 15mm, Smooth, 0.0150, 0.160, 600.0, 1000.0;
Material, Concrete 150mm, MediumRough, 0.1500, 1.730, 2243.0, 837.0;
Material, Roof Membrane, VeryRough, 0.0095, 0.160, 1121.0, 1460.0;

WindowMaterial:SimpleGlazingSystem,
    Simple Glazing, 2.500, 0.350, 0.700;

Construction, ExtWall,  Brick 200mm, Insulation 80mm, Plaster 15mm;
Construction, ExtRoof,  Roof Membrane, Insulation 80mm, Concrete 150mm;
Construction, ExtFloor, Concrete 150mm;
Construction, ExtWindow, Simple Glazing;

Zone,
    {zone},                  !- Name
    0.0,                     !- Direction of Relative North {{deg}}
    0.0, 0.0, 0.0,           !- X, Y, Z Origin {{m}}
    1,                       !- Type
    1,                       !- Multiplier
    autocalculate,           !- Ceiling Height {{m}}
    autocalculate,           !- Volume {{m3}}
    autocalculate,           !- Floor Area {{m2}}
    ,                        !- Zone Inside Convection Algorithm
    ,                        !- Zone Outside Convection Algorithm
    Yes;                     !- Part of Total Floor Area

Output:VariableDictionary, IDF;
Output:Surfaces:Drawing, DXF;
Output:Diagnostics, DisplayExtraWarnings;
"""

CONSTRUCTION = {"Wall": "ExtWall", "Roof": "ExtRoof", "Floor": "ExtFloor"}

def load_points(path):
    if path is None or not os.path.exists(path):
        return np.zeros((0, 3))
    return np.asarray(o3d.io.read_point_cloud(path).points)

def read_directions(path):
    if path is None:
        return None
    rows = []
    with open(path) as handle:
        for line in handle:
            line = line.strip()
            if line and not line.startswith("#"):
                rows.append([float(x) for x in line.replace(",", " ").split()])
    return np.array(rows, float) if rows else None

def building_frame(directions, points):
    """Rotation whose Z is up and whose X follows the building's long axis."""
    if directions is None or len(directions) < 3:
        flat = points[:, :2] - points[:, :2].mean(axis=0)
        _, vectors = np.linalg.eigh(flat.T @ flat)
        x_axis = np.array([vectors[0, -1], vectors[1, -1], 0.0])
    else:
        unit = directions / np.linalg.norm(directions, axis=1, keepdims=True)
        up = int(np.argmax(np.abs(unit[:, 2])))
        x_axis = np.array(
            [unit[i] for i in range(len(unit)) if i != up][0], float)
        x_axis[2] = 0.0

    if np.linalg.norm(x_axis) < 1e-9:
        x_axis = np.array([1.0, 0.0, 0.0])
    if x_axis[0] < 0 or (abs(x_axis[0]) < 1e-9 and x_axis[1] < 0):
        x_axis = -x_axis                     # keep the frame canonical
    x_axis /= np.linalg.norm(x_axis)
    z_axis = np.array([0.0, 0.0, 1.0])
    y_axis = np.cross(z_axis, x_axis)
    rotation = np.vstack([x_axis, y_axis, z_axis])
    north = float(np.degrees(np.arctan2(x_axis[1], x_axis[0])))
    return rotation, north

def polygon_normal(vertices):
    normal = np.zeros(3)
    for i in range(len(vertices)):
        normal += np.cross(vertices[i], vertices[(i + 1) % len(vertices)])
    length = np.linalg.norm(normal)
    return normal / length if length else normal

def polygon_area(vertices):
    total = np.zeros(3)
    for i in range(len(vertices)):
        total += np.cross(vertices[i], vertices[(i + 1) % len(vertices)])
    return 0.5 * np.linalg.norm(total)

def orient(vertices, outward):
    """EnergyPlus wants vertices counter-clockwise seen from outside,
    starting at the upper-left corner."""
    v = list(vertices)
    if polygon_normal(v) @ outward < 0:
        v = v[::-1]

    left = np.cross(np.array([0.0, 0.0, 1.0]), outward)
    if np.linalg.norm(left) < 1e-9:
        left = np.array([1.0, 0.0, 0.0])
    left /= np.linalg.norm(left)

    keys = np.array([[-round(p[2], 4), round(float(p @ left), 4)] for p in v])
    start = int(np.lexsort((keys[:, 1], keys[:, 0]))[0])
    return v[start:] + v[:start]

def vertex_block(vertices, indent="    "):
    lines = []
    for number, point in enumerate(vertices, start=1):
        end = ";" if number == len(vertices) else ","
        lines.append(f"{indent}{point[0]:.4f}, {point[1]:.4f}, "
                     f"{point[2]:.4f}{end}  !- Vertex {number} X,Y,Z")
    return "\n".join(lines)

def write_idf(path, surfaces, windows, shades, zone, north, version, name):
    blocks = [HEADER.format(version=version, north=north, zone=zone,
                            name=name)]

    for surface in surfaces:
        kind = surface["type"]
        if kind == "Floor":
            boundary, sun, wind = "Ground", "NoSun", "NoWind"
        else:
            boundary, sun, wind = "Outdoors", "SunExposed", "WindExposed"

        blocks.append(
            "BuildingSurface:Detailed,\n"
            f"    {surface['name']},\n"
            f"    {kind},\n"
            f"    {CONSTRUCTION[kind]},\n"
            f"    {zone},\n"
            "    ,                        !- Space Name\n"
            f"    {boundary},\n"
            "    ,                        !- Outside Boundary Condition Object\n"
            f"    {sun},\n"
            f"    {wind},\n"
            "    ,                        !- View Factor to Ground\n"
            f"    {len(surface['vertices'])},  !- Number of Vertices\n"
            + vertex_block(surface["vertices"]))

    for window in windows:
        blocks.append(
            "FenestrationSurface:Detailed,\n"
            f"    {window['name']},\n"
            "    Window,\n"
            "    ExtWindow,\n"
            f"    {window['wall']},\n"
            "    ,                        !- Outside Boundary Condition Object\n"
            "    ,                        !- View Factor to Ground\n"
            "    ,                        !- Frame and Divider Name\n"
            "    1,                       !- Multiplier\n"
            "    4,                       !- Number of Vertices\n"
            + vertex_block(window["vertices"]))

    for shade in shades:
        blocks.append(
            "Shading:Building:Detailed,\n"
            f"    {shade['name']},\n"
            "    ,                        !- Transmittance Schedule Name\n"
            "    4,                       !- Number of Vertices\n"
            + vertex_block(shade["vertices"]))

    with open(path, "w") as handle:
        handle.write("\n\n".join(blocks) + "\n")

def write_preview(path, surfaces, windows, shades):
    """One coloured mesh so the result can be opened next to the cloud."""
    palette = {"Wall": [0.75, 0.75, 0.78], "Roof": [0.85, 0.30, 0.25],
               "Floor": [0.25, 0.35, 0.65], "Window": [0.20, 0.85, 0.95],
               "Column": [1.00, 0.80, 0.20]}

    vertices, triangles, colours = [], [], []

    def add(polygon, colour):
        base = len(vertices)
        vertices.extend(polygon)
        colours.extend([colour] * len(polygon))
        for i in range(1, len(polygon) - 1):
            triangles.append([base, base + i, base + i + 1])

    for surface in surfaces:
        add(surface["vertices"], palette[surface["type"]])
    for window in windows:
        add(window["vertices"], palette["Window"])
    for shade in shades:
        add(shade["vertices"], palette["Column"])

    mesh = o3d.geometry.TriangleMesh()
    mesh.vertices = o3d.utility.Vector3dVector(np.array(vertices))
    mesh.triangles = o3d.utility.Vector3iVector(
        np.array(triangles, dtype=np.int32))
    mesh.vertex_colors = o3d.utility.Vector3dVector(np.array(colours))
    mesh.compute_vertex_normals()
    o3d.io.write_triangle_mesh(path, mesh)

def write_scaled_cloud(path, blocks):
    """The input clouds after rotation and scaling, for side-by-side checks."""
    points, colours = [], []
    palette = {"envelope": [0.85, 0.30, 0.25], "window": [0.20, 0.85, 0.95],
               "column": [1.00, 0.80, 0.20]}
    for name, data in blocks.items():
        if len(data):
            points.append(data)
            colours.append(np.tile(palette[name], (len(data), 1)))
    if not points:
        return
    cloud = o3d.geometry.PointCloud()
    cloud.points = o3d.utility.Vector3dVector(np.vstack(points))
    cloud.colors = o3d.utility.Vector3dVector(np.vstack(colours))
    o3d.io.write_point_cloud(path, cloud)

def closure_report(surfaces):
    """Divergence theorem: a closed surface has sum(area * normal) == 0."""
    total_area = sum(s["area"] for s in surfaces)
    imbalance = np.zeros(3)
    volume = 0.0
    for s in surfaces:
        imbalance += s["area"] * s["outward"]
        centroid = np.mean(s["vertices"], axis=0)
        volume += (centroid @ s["outward"]) * s["area"] / 3.0
    return total_area, float(np.linalg.norm(imbalance)), volume


# --------------------------------------------------------------------------
# 1. vertical facade planes
# --------------------------------------------------------------------------

def estimate_normals(points, radius, max_nn=40):
    cloud = o3d.geometry.PointCloud()
    cloud.points = o3d.utility.Vector3dVector(points)
    cloud.estimate_normals(
        search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=radius,
                                                          max_nn=max_nn))
    normals = np.asarray(cloud.normals)
    length = np.linalg.norm(normals, axis=1, keepdims=True)
    length[length == 0] = 1.0
    return normals / length


def facade_directions(normals, vertical_angle, bins, min_share):
    """Angles, in plan, of the facade planes. Handles non-Manhattan walls."""
    horizontal = np.abs(normals[:, 2]) < np.sin(np.deg2rad(vertical_angle))
    flat = normals[horizontal][:, :2]
    if len(flat) == 0:
        return [], horizontal

    angle = np.degrees(np.arctan2(flat[:, 1], flat[:, 0])) % 180.0
    counts, edges = np.histogram(angle, bins=bins, range=(0.0, 180.0))
    # the histogram wraps at 180 degrees
    wrapped = np.r_[counts, counts, counts].astype(float)
    smooth = ndimage.uniform_filter1d(wrapped, size=3)[bins:2 * bins]

    peaks, _ = find_peaks(np.r_[smooth[-1], smooth, smooth[0]],
                          height=min_share * smooth.max(), distance=2)
    peaks = [p - 1 for p in peaks if 0 <= p - 1 < bins]
    centers = 0.5 * (edges[:-1] + edges[1:])
    return sorted(float(centers[p]) for p in peaks), horizontal


def plane_offsets(values, thickness, min_points, peak_ratio):
    if len(values) < min_points:
        return []
    width = thickness / 2.0
    pad = 4 * thickness
    low, high = values.min() - pad, values.max() + pad
    counts, edges = np.histogram(
        values, bins=max(int(np.ceil((high - low) / width)), 8),
        range=(low, high))
    window = max(int(round(thickness / width)), 1)
    smooth = np.convolve(counts.astype(float), np.ones(2 * window + 1),
                         mode="same")
    if smooth.max() <= 0:
        return []

    floor_value = max(min_points, peak_ratio * smooth.max())
    peaks, _ = find_peaks(smooth, height=floor_value,
                          prominence=0.25 * floor_value,
                          distance=max(int(round(2 * thickness / width)), 1))
    centers = 0.5 * (edges[:-1] + edges[1:])

    out = []
    for peak in peaks:
        offset = centers[peak]
        for _ in range(4):
            near = np.abs(values - offset) <= thickness
            if np.count_nonzero(near) < min_points:
                break
            offset = float(np.median(values[near]))
        near = np.abs(values - offset) <= thickness
        if np.count_nonzero(near) >= min_points:
            out.append((offset, int(np.count_nonzero(near))))
    return out


def facade_lines(points, normals, thickness, min_points, peak_ratio,
                 vertical_angle, angle_bins, angle_share, angle_tol,
                 max_lines):
    """Return [(unit normal in plan, offset, support)] for the facades."""
    angles, horizontal = facade_directions(normals, vertical_angle,
                                           angle_bins, angle_share)
    if not angles:
        return []

    flat_points = points[horizontal][:, :2]
    flat_normals = normals[horizontal][:, :2]
    length = np.linalg.norm(flat_normals, axis=1, keepdims=True)
    length[length == 0] = 1.0
    flat_normals = flat_normals / length

    limit = np.cos(np.deg2rad(angle_tol))
    lines = []
    for angle in angles:
        direction = np.array([np.cos(np.deg2rad(angle)),
                              np.sin(np.deg2rad(angle))])
        aligned = np.abs(flat_normals @ direction) >= limit
        chosen = flat_points[aligned]
        if len(chosen) < min_points:
            continue
        for offset, support in plane_offsets(chosen @ direction, thickness,
                                             min_points, peak_ratio):
            lines.append((direction, offset, support))

    lines.sort(key=lambda item: -item[2])
    return lines[:max_lines]


# --------------------------------------------------------------------------
# 2. plan arrangement
# --------------------------------------------------------------------------

def arrangement(lines, bounds, margin):
    xmin, ymin, xmax, ymax = bounds
    frame = box(xmin - margin, ymin - margin, xmax + margin, ymax + margin)
    reach = 2.0 * (abs(xmax - xmin) + abs(ymax - ymin))

    segments = [LineString(frame.exterior.coords)]
    for direction, offset, _ in lines:
        along = np.array([-direction[1], direction[0]])
        middle = direction * offset
        segments.append(LineString([tuple(middle - along * reach),
                                    tuple(middle + along * reach)]))

    noded = unary_union(segments)
    faces = [f for f in polygonize(noded) if f.is_valid and not f.is_empty]
    return faces


def occupancy_grid(points, cell, min_hits, percentile):
    x0, y0 = points[:, 0].min(), points[:, 1].min()
    ix = np.floor((points[:, 0] - x0) / cell).astype(int)
    iy = np.floor((points[:, 1] - y0) / cell).astype(int)
    shape = (int(ix.max()) + 1, int(iy.max()) + 1)

    counts = np.zeros(shape, dtype=np.int32)
    np.add.at(counts, (ix, iy), 1)

    heights = np.zeros(shape)
    flat = ix * shape[1] + iy
    order = np.lexsort((points[:, 2], flat))
    flat, z = flat[order], points[order, 2]
    breaks = np.r_[0, np.flatnonzero(np.diff(flat)) + 1, len(flat)]
    for start, stop in zip(breaks[:-1], breaks[1:]):
        key = flat[start]
        heights[key // shape[1], key % shape[1]] = \
            np.percentile(z[start:stop], percentile)

    mask = counts >= min_hits
    centres, values = [], []
    for i, j in zip(*np.nonzero(mask)):
        centres.append(((i + 0.5) * cell + x0, (j + 0.5) * cell + y0))
        values.append(heights[i, j])
    return np.array(centres), np.array(values)


def label_faces(faces, centres, values, cell, min_fill, min_area,
                cell_percentile):
    """Decide which arrangement cells are inside the building, and how tall."""
    tree = STRtree([Point(p) for p in centres])
    inside, heights = [], []

    for face in faces:
        if face.area < min_area:
            inside.append(False)
            heights.append(0.0)
            continue

        hits = tree.query(face)
        if len(hits):
            keep = [k for k in hits if face.contains(Point(centres[k]))]
        else:
            keep = []

        covered = len(keep) * cell * cell
        fill = covered / face.area
        if fill < min_fill or len(keep) < 2:
            inside.append(False)
            heights.append(0.0)
        else:
            # median, not a high percentile: a cell touching the tower would
            # otherwise inherit the tower's height from a few boundary cells
            inside.append(True)
            heights.append(float(np.percentile(values[keep],
                                               cell_percentile)))
    return np.array(inside), np.array(heights)


def quantize_heights(heights, inside, count, tolerance):
    live = heights[inside]
    if live.size == 0:
        raise SystemExit("no arrangement cell is inside the building")

    counts, edges = np.histogram(live, bins=60)
    centers = 0.5 * (edges[:-1] + edges[1:])
    peaks, _ = find_peaks(np.r_[0, counts, 0], distance=2)
    peaks = [p - 1 for p in peaks if 0 <= p - 1 < len(centers)]
    peaks.sort(key=lambda p: -counts[p])

    levels = sorted(float(centers[p]) for p in peaks[:count])
    if not levels:
        levels = [float(np.median(live))]
    if live.max() - max(levels) > tolerance:
        levels.append(float(live.max()))

    snapped = heights.copy()
    for index in np.flatnonzero(inside):
        nearest = min(levels, key=lambda v: abs(v - heights[index]))
        if abs(nearest - heights[index]) <= tolerance:
            snapped[index] = nearest
        else:
            levels.append(float(heights[index]))
            snapped[index] = heights[index]
    return snapped, sorted(set(round(v, 3) for v in levels))


# --------------------------------------------------------------------------
# 3. extrusion
# --------------------------------------------------------------------------

def key_of(point, places=4):
    return (round(point[0], places), round(point[1], places))


def extrude(faces, inside, heights):
    """Floor, roof and walls of the labelled arrangement."""
    surfaces = []
    edges = defaultdict(list)

    for index, face in enumerate(faces):
        if not inside[index]:
            continue
        ring = list(face.exterior.coords)[:-1]
        height = heights[index]

        floor = [np.array([x, y, 0.0]) for x, y in ring]
        surfaces.append({"type": "Floor", "outward": np.array([0., 0., -1.]),
                         "vertices": orient(floor, np.array([0., 0., -1.]))})

        roof = [np.array([x, y, height]) for x, y in ring]
        surfaces.append({"type": "Roof", "outward": np.array([0., 0., 1.]),
                         "vertices": orient(roof, np.array([0., 0., 1.]))})

        for a, b in zip(ring, ring[1:] + ring[:1]):
            edges[tuple(sorted((key_of(a), key_of(b))))].append(index)

    # collect every edge of the arrangement, including the outer boundary
    for index, face in enumerate(faces):
        ring = list(face.exterior.coords)[:-1]
        for a, b in zip(ring, ring[1:] + ring[:1]):
            key = tuple(sorted((key_of(a), key_of(b))))
            if index not in edges[key]:
                edges[key].append(index)

    for (pa, pb), owners in edges.items():
        levels = []
        for index in owners:
            levels.append(heights[index] if inside[index] else 0.0)
        while len(levels) < 2:
            levels.append(0.0)
        if len(levels) > 2:
            levels = sorted(levels)[-2:]

        low, high = min(levels), max(levels)
        if high - low < 1e-6:
            continue

        tall = owners[int(np.argmax([
            heights[i] if inside[i] else 0.0 for i in owners]))]
        along = np.array([pb[0] - pa[0], pb[1] - pa[1]])
        if np.linalg.norm(along) < 1e-9:
            continue
        outward = np.array([along[1], -along[0]])
        outward /= np.linalg.norm(outward)

        middle = np.array([(pa[0] + pb[0]) / 2, (pa[1] + pb[1]) / 2])
        centre = np.array(faces[tall].centroid.coords[0])
        if outward @ (middle - centre) < 0:
            outward = -outward

        quad = [np.array([pa[0], pa[1], low]), np.array([pb[0], pb[1], low]),
                np.array([pb[0], pb[1], high]), np.array([pa[0], pa[1], high])]
        surfaces.append({"type": "Wall",
                         "outward": np.array([outward[0], outward[1], 0.0]),
                         "vertices": orient(quad, np.array([outward[0],
                                                            outward[1], 0.0]))})

    for number, surface in enumerate(surfaces, start=1):
        surface["name"] = f"{surface['type']}_{number:04d}"
        surface["area"] = polygon_area(surface["vertices"])
    return surfaces


# --------------------------------------------------------------------------
# 4. windows, found on each wall's own plane
# --------------------------------------------------------------------------

def wall_frame(surface):
    outward = surface["outward"]
    horizontal = np.cross(np.array([0.0, 0.0, 1.0]), outward)
    horizontal /= np.linalg.norm(horizontal)
    vertical = np.array([0.0, 0.0, 1.0])
    origin = surface["vertices"][0]
    a = [float((p - origin) @ horizontal) for p in surface["vertices"]]
    b = [float((p - origin) @ vertical) for p in surface["vertices"]]
    return origin, horizontal, vertical, (min(a), max(a)), (min(b), max(b))


def windows_on_walls(points, walls, band, cell, margin, min_size, min_points,
                     reach):
    """Assign each glazing point to its nearest wall, then cut it up.

    reach: slack on the wall rectangle. A wall is one arrangement edge, so a
    window sitting just past a corner would otherwise find no host.
    """
    if len(points) == 0 or not walls:
        return [], {"unassigned": 0, "unassigned_points": points}

    best = np.full(len(points), -1)
    best_distance = np.full(len(points), band)

    for index, wall in enumerate(walls):
        origin, ha, va, arange, brange = wall["frame"]
        delta = points - origin
        distance = np.abs(delta @ wall["outward"])
        a = delta @ ha
        b = delta @ va
        ok = ((distance < best_distance)
              & (a >= arange[0] - reach) & (a <= arange[1] + reach)
              & (b >= brange[0] - reach) & (b <= brange[1] + reach))
        best[ok] = index
        best_distance[ok] = distance[ok]

    windows = []
    orphans = points[best < 0]
    unassigned = int(len(orphans))

    for index, wall in enumerate(walls):
        chosen = points[best == index]
        if len(chosen) < min_points:
            continue

        origin, ha, va, arange, brange = wall["frame"]
        delta = chosen - origin
        a = delta @ ha
        b = delta @ va

        a = np.clip(a, arange[0], arange[1])
        b = np.clip(b, brange[0], brange[1])
        ia = np.floor((a - arange[0]) / cell).astype(int)
        ib = np.floor((b - brange[0]) / cell).astype(int)
        shape = (int(ia.max()) + 1, int(ib.max()) + 1)
        grid = np.zeros(shape, dtype=np.int32)
        np.add.at(grid, (ia, ib), 1)

        mask = grid >= 1
        mask = ndimage.binary_closing(mask, structure=np.ones((2, 2), bool))
        mask = ndimage.binary_fill_holes(mask)
        labels, total = ndimage.label(mask, structure=np.ones((3, 3)))

        count = 0
        for region in range(1, total + 1):
            piece = labels == region
            if grid[piece].sum() < min_points:
                continue
            ri, ci = np.nonzero(piece)
            amin = arange[0] + ri.min() * cell
            amax = arange[0] + (ri.max() + 1) * cell
            bmin = brange[0] + ci.min() * cell
            bmax = brange[0] + (ci.max() + 1) * cell

            amin = max(amin, arange[0] + margin)
            amax = min(amax, arange[1] - margin)
            bmin = max(bmin, brange[0] + margin)
            bmax = min(bmax, brange[1] - margin)
            if amax - amin < min_size or bmax - bmin < min_size:
                continue

            count += 1
            quad = [origin + ha * amin + va * bmin,
                    origin + ha * amax + va * bmin,
                    origin + ha * amax + va * bmax,
                    origin + ha * amin + va * bmax]
            windows.append({"name": f"{wall['name']}_Win_{count:02d}",
                            "wall": wall["name"],
                            "vertices": orient(quad, wall["outward"]),
                            "area": (amax - amin) * (bmax - bmin)})

    return windows, {"unassigned": unassigned, "unassigned_points": orphans}


# --------------------------------------------------------------------------
# 5. columns as shading
# --------------------------------------------------------------------------

def column_shades(points, eps, min_points, min_height, max_width,
                  min_slenderness):
    if len(points) < min_points:
        return [], {"too_short": 0, "too_wide": 0, "too_fat": 0}, []

    cloud = o3d.geometry.PointCloud()
    cloud.points = o3d.utility.Vector3dVector(points)
    labels = np.array(cloud.cluster_dbscan(eps=eps, min_points=min_points,
                                           print_progress=False))

    shades = []
    rejected = {"too_short": 0, "too_wide": 0, "too_fat": 0}
    measured = []
    kept = 0

    for group_id in range(labels.max() + 1):
        group = points[labels == group_id]
        low, high = group[:, 2].min(), group[:, 2].max()

        plan = Polygon(group[:, :2]).convex_hull.minimum_rotated_rectangle
        if plan.is_empty or plan.geom_type != "Polygon":
            rejected["too_wide"] += 1
            continue
        ring = list(plan.exterior.coords)[:-1]
        sides = [np.hypot(ring[i][0] - ring[(i + 1) % 4][0],
                          ring[i][1] - ring[(i + 1) % 4][1])
                 for i in range(4)]
        width = max(sides)
        measured.append((high - low, width, len(group)))

        if high - low < min_height:
            rejected["too_short"] += 1
            continue
        if width > max_width:
            rejected["too_wide"] += 1
            continue
        if (high - low) / max(width, 1e-6) < min_slenderness:
            rejected["too_fat"] += 1
            continue

        kept += 1
        centre = np.array(plan.centroid.coords[0])
        for side in range(4):
            pa, pb = ring[side], ring[(side + 1) % 4]
            along = np.array([pb[0] - pa[0], pb[1] - pa[1]])
            if np.linalg.norm(along) < 1e-9:
                continue
            outward = np.array([along[1], -along[0]])
            outward /= np.linalg.norm(outward)
            middle = np.array([(pa[0] + pb[0]) / 2, (pa[1] + pb[1]) / 2])
            if outward @ (middle - centre) < 0:
                outward = -outward
            quad = [np.array([pa[0], pa[1], low]),
                    np.array([pb[0], pb[1], low]),
                    np.array([pb[0], pb[1], high]),
                    np.array([pa[0], pa[1], high])]
            shades.append({
                "name": f"Column_{kept:03d}_S{side + 1}",
                "vertices": orient(quad, np.array([outward[0], outward[1],
                                                   0.0]))})
    return shades, rejected, measured


# --------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--envelope", required=True)
    parser.add_argument("--windows", default=None)
    parser.add_argument("--columns", default=None)
    parser.add_argument("--dirs", default=None)
    parser.add_argument("--out", default="building.idf")
    parser.add_argument("--height", type=float, required=True)

    parser.add_argument("--plane-thickness", type=float, default=0.5,
                        help="facade plane slab half width, metres")
    parser.add_argument("--plane-min-points", type=int, default=400)
    parser.add_argument("--plane-peak-ratio", type=float, default=0.04)
    parser.add_argument("--max-lines", type=int, default=20,
                        help="how many facade lines enter the arrangement")
    parser.add_argument("--vertical-angle", type=float, default=25.0)
    parser.add_argument("--angle-bins", type=int, default=90)
    parser.add_argument("--angle-share", type=float, default=0.25)
    parser.add_argument("--angle-tol", type=float, default=15.0)

    parser.add_argument("--cell", type=float, default=0.6,
                        help="occupancy sampling cell, metres")
    parser.add_argument("--min-hits", type=int, default=4)
    parser.add_argument("--min-fill", type=float, default=0.35,
                        help="share of a cell that must hold points")
    parser.add_argument("--min-cell-area", type=float, default=1.0)
    parser.add_argument("--top-percentile", type=float, default=95.0,
                        help="top of the envelope inside one sampling cell")
    parser.add_argument("--cell-percentile", type=float, default=50.0,
                        help="height of an arrangement cell, across its "
                             "sampling cells. Keep this near 50")
    parser.add_argument("--levels", type=int, default=4)
    parser.add_argument("--level-tolerance", type=float, default=3.0)

    parser.add_argument("--window-band", type=float, default=1.2)
    parser.add_argument("--window-cell", type=float, default=0.25)
    parser.add_argument("--window-margin", type=float, default=0.15)
    parser.add_argument("--window-min-size", type=float, default=0.5)
    parser.add_argument("--window-min-points", type=int, default=25)
    parser.add_argument("--window-reach", type=float, default=0.5,
                        help="slack on the wall rectangle, metres")
    parser.add_argument("--orphans", default=None,
                        help="write the glazing points that found no wall, "
                             "e.g. --orphans orphans.ply")

    parser.add_argument("--column-eps", type=float, default=0.5)
    parser.add_argument("--column-min-points", type=int, default=60)
    parser.add_argument("--column-min-height", type=float, default=2.0)
    parser.add_argument("--column-max-width", type=float, default=2.5)
    parser.add_argument("--column-slenderness", type=float, default=1.5)

    parser.add_argument("--preview", default=None)
    parser.add_argument("--preview-cloud", default=None)
    parser.add_argument("--zone", default="Zone_Building")
    parser.add_argument("--name", default="LSU Tower")
    parser.add_argument("--version", default="24.1")
    args = parser.parse_args()

    envelope = load_points(args.envelope)
    glazing = load_points(args.windows)
    columns = load_points(args.columns)
    if len(envelope) == 0:
        raise SystemExit(f"no points in {args.envelope}")
    print(f"envelope {len(envelope)}  windows {len(glazing)}  "
          f"columns {len(columns)}")

    rotation, north = building_frame(read_directions(args.dirs), envelope)
    envelope = envelope @ rotation.T
    glazing = glazing @ rotation.T if len(glazing) else glazing
    columns = columns @ rotation.T if len(columns) else columns

    span = envelope[:, 2].max() - envelope[:, 2].min()
    scale = args.height / span
    origin = np.array([envelope[:, 0].min(), envelope[:, 1].min(),
                       envelope[:, 2].min()])
    envelope = (envelope - origin) * scale
    glazing = (glazing - origin) * scale if len(glazing) else glazing
    columns = (columns - origin) * scale if len(columns) else columns
    print(f"north axis {north:.2f} deg, scale {scale:.3f} "
          f"(height {args.height:.1f} m)")

    facade_points = envelope if len(glazing) == 0 else \
        np.vstack([envelope, glazing])

    spacing = args.cell / 3.0
    normals = estimate_normals(facade_points, radius=max(spacing, 0.25) * 3)

    lines = facade_lines(facade_points, normals, args.plane_thickness,
                         args.plane_min_points, args.plane_peak_ratio,
                         args.vertical_angle, args.angle_bins,
                         args.angle_share, args.angle_tol, args.max_lines)
    print(f"facade lines {len(lines)}")
    if len(lines) < 4:
        raise SystemExit("too few facade planes - lower --plane-min-points "
                         "or --plane-peak-ratio")

    bounds = (facade_points[:, 0].min(), facade_points[:, 1].min(),
              facade_points[:, 0].max(), facade_points[:, 1].max())
    faces = arrangement(lines, bounds, margin=2.0)
    print(f"arrangement cells {len(faces)}")

    centres, values = occupancy_grid(facade_points, args.cell, args.min_hits,
                                     args.top_percentile)
    inside, heights = label_faces(faces, centres, values, args.cell,
                                  args.min_fill, args.min_cell_area,
                                  args.cell_percentile)
    heights, levels = quantize_heights(heights, inside, args.levels,
                                       args.level_tolerance)
    footprint = sum(f.area for f, keep in zip(faces, inside) if keep)
    print(f"inside cells {int(inside.sum())}, footprint {footprint:.0f} m2")
    print(f"levels {[round(v, 1) for v in levels]} m")

    surfaces = extrude(faces, inside, heights)
    walls = [s for s in surfaces if s["type"] == "Wall"]
    for wall in walls:
        wall["frame"] = wall_frame(wall)

    area, imbalance, volume = closure_report(surfaces)
    print(f"surfaces {len(surfaces)} ({len(walls)} wall, "
          f"{sum(1 for s in surfaces if s['type'] == 'Roof')} roof, "
          f"{sum(1 for s in surfaces if s['type'] == 'Floor')} floor)")
    print(f"total area {area:.1f} m2, volume {volume:.1f} m3")
    closed = imbalance < 1e-6 * max(area, 1.0)
    print(f"closure error {imbalance:.6f} m2 "
          f"({'closed' if closed else 'NOT CLOSED'})")

    placed, report = windows_on_walls(glazing, walls, args.window_band,
                                      args.window_cell, args.window_margin,
                                      args.window_min_size,
                                      args.window_min_points,
                                      args.window_reach)
    share = 100.0 * report["unassigned"] / max(len(glazing), 1)
    hosts = len({w["wall"] for w in placed})
    print(f"windows {len(placed)} placed on {hosts} of {len(walls)} walls "
          f"({report['unassigned']} points, {share:.0f}%, found no wall)")
    if args.orphans and len(report["unassigned_points"]):
        write_scaled_cloud(args.orphans,
                           {"window": report["unassigned_points"]})
        print(f"  wrote {args.orphans}")

    shades, rejected, measured = column_shades(
        columns, args.column_eps, args.column_min_points,
        args.column_min_height, args.column_max_width,
        args.column_slenderness)
    print(f"columns {len(shades) // 4} kept -> {len(shades)} shading surfaces"
          + (f" (rejected {rejected['too_short']} short, "
             f"{rejected['too_wide']} wide, {rejected['too_fat']} fat)"
             if sum(rejected.values()) else ""))
    if measured:
        tall = np.array([m[0] for m in measured])
        wide = np.array([m[1] for m in measured])
        print(f"  cluster heights m: min {tall.min():.1f}  "
              f"median {np.median(tall):.1f}  max {tall.max():.1f}"
              f"   (--column-min-height {args.column_min_height})")
        print(f"  cluster widths  m: min {wide.min():.1f}  "
              f"median {np.median(wide):.1f}  max {wide.max():.1f}"
              f"   (--column-max-width {args.column_max_width})")

    write_idf(args.out, surfaces, placed, shades, args.zone, north,
              args.version, args.name)
    print(f"\nwrote {args.out}")
    if args.preview:
        write_preview(args.preview, surfaces, placed, shades)
        print(f"wrote {args.preview}")
    if args.preview_cloud:
        write_scaled_cloud(args.preview_cloud,
                           {"envelope": envelope, "window": glazing,
                            "column": columns})
        print(f"wrote {args.preview_cloud}")


if __name__ == "__main__":
    main()
